blogvalidatorweb/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url('', include('crawl.urls')),
]

crawl/urls.py
from django.conf.urls import url

from . import views
app_name = 'crawl'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<sitename>.+)/$', views.list, name='image_list'),
    url(r'^(?P<sitename>.+)/(?P<sort>[vasm])$', views.list, name='image_list'),
    url(r'^(?P<sitename>.+)/(?P<page>[0-9]+)$', views.list, name='image_list'),
    url(r'^(?P<sitename>.+)/(?P<sort>[vasm])/(?P<page>[0-9]+)$', views.list, name='image_list'),
]

crawl/models.py
from django.db import models
from django.db.models import Count, Case, When, Value, IntegerField


class Item(models.Model):
    name = models.CharField(max_length=200, null=False)
    url = models.CharField(max_length=1000, null=True)
    violence = models.CharField(max_length=200, null=True)
    adult = models.CharField(max_length=200, null=True)
    spoof = models.CharField(max_length=200, null=True)
    medical = models.CharField(max_length=200, null=True)
    page_title = models.CharField(max_length=1000, null=True)
    page_url = models.CharField(max_length=1000, null=True)
    site_name = models.CharField(max_length=1000, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    values = {
        'VERY_UNLIKELY': 1,
        'UNLIKELY': 2,
        'POSSIBLE': 3,
        'LIKELY': 4,
        'VERY_LIKELY': 5,
    }

    def evalue_violence(self):
        return self.evalue(self.violence)

    def evalue_adult(self):
        return self.evalue(self.adult)

    def evalue_spoof(self):
        return self.evalue(self.spoof)

    def evalue_medical(self):
        return self.evalue(self.medical)

    def evalue(self, kind_column):
        """
        usage:
            x=models.Item.objects.all()[0]
            x.evalue(x.violence)
        """
        return self.values.get(kind_column) or 0


def get_sitenames():
    return Item.objects.values('site_name').annotate(icount=Count('site_name'))


def get_images_by_sitename(sitename, sort='v'):

    if sort == 'v':
        order = '-eval_violence'
    elif sort == 'a':
        order = '-eval_adult'
    elif sort == 's':
        order = '-eval_spoof'
    else:
        order = '-eval_medical'

    return Item.objects.filter(site_name=sitename).annotate(
            eval_violence=Case(When(violence='VERY_UNLIKELY', then=Value(1)),
                               When(violence='UNLIKELY', then=Value(2)),
                               When(violence='POSSIBLE', then=Value(3)),
                               When(violence='LIKELY', then=Value(4)),
                               When(violence='VERY_LIKELY', then=Value(5)),
                               default=Value(0), output_field=IntegerField()),
            eval_adult=Case(When(adult='VERY_UNLIKELY', then=Value(1)),
                            When(adult='UNLIKELY', then=Value(2)),
                            When(adult='POSSIBLE', then=Value(3)),
                            When(adult='LIKELY', then=Value(4)),
                            When(adult='VERY_LIKELY', then=Value(5)),
                            default=Value(0), output_field=IntegerField()),
            eval_spoof=Case(When(spoof='VERY_UNLIKELY', then=Value(1)),
                            When(spoof='UNLIKELY', then=Value(2)),
                            When(spoof='POSSIBLE', then=Value(3)),
                            When(spoof='LIKELY', then=Value(4)),
                            When(spoof='VERY_LIKELY', then=Value(5)),
                            default=Value(0), output_field=IntegerField()),
            eval_medical=Case(When(medical='VERY_UNLIKELY', then=Value(1)),
                              When(medical='UNLIKELY', then=Value(2)),
                              When(medical='POSSIBLE', then=Value(3)),
                              When(medical='LIKELY', then=Value(4)),
                              When(medical='VERY_LIKELY', then=Value(5)),
                              default=Value(0), output_field=IntegerField()),
            ).values('name', 'url', 'violence', 'adult', 'spoof', 'medical',
                     'page_title', 'page_url', 'site_name', 'created_at', 'updated_at',
                     'eval_violence', 'eval_adult', 'eval_spoof', 'eval_medical'
            ).order_by(order)

crawl/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import csv
import datetime
from .models import get_sitenames
from .models import get_images_by_sitename


def index(request):
    return render(request, 'index.html', {'sites': get_sitenames()})


def list(request, sitename, page='1', sort='v'):
    paginator = Paginator(get_images_by_sitename(sitename, sort), 100)

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    return render(request, 'list.html', {'sitename': sitename, 'items': items})

crawl/templates/_level.html
{% spaceless %}
<td style="background-color:
{% if lv == 5 %}
#f00
{% elif lv == 4 %}
#fa0
{% elif lv == 3 %}
#ff0
{% elif lv == 2 %}
#af0
{% elif lv == 1 %}
#0f0
{% endif %}
">{{ lv }} </td>
{% endspaceless %}

crawl/templates/_pagination.html
<nav>
  <ul class="pagination">
    {% if not items.has_previous %}
        <li class="disabled"><a href="#">prev</a></li>
    {% else %}
        <li><a href="{% url 'crawl:image_list' sitename items.previous_page_number %}">prev</a></li>
    {% endif %}

    {% for page_link in items.paginator.page_range %}
        {% if page_link == items.number %}
            <li class="active"><a href="{% url 'crawl:image_list' sitename page_link %}">{{page_link}}</a></li>
        {% else %}
            <li><a href="{% url 'crawl:image_list' sitename page_link %}">{{page_link}}</a></li>
        {% endif %}
    {% endfor %}

    {% if not items.has_next %}
        <li class="disabled"><a href="#">next</a></li>
    {% else %}
        <li><a href="{% url 'crawl:image_list' sitename items.next_page_number %}">next</a></li>
    {% endif %}
  </ul>
</nav>

crawl/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>blogvalidator web</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-2.2.2.min.js" integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js" integrity="sha256-xNjb53/rY+WmG+4L6tTl9m6PpqknWZvRt0rO1SRnJzw=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block head %}
    {% endblock %}
</head>

<body>

<div id="content">
{% block content %}
{% endblock %}
</div>

</body>
</html>

crawl/templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>sites</h1>
<div class="table-responsive">
{% if not sites %}
    <p>Site not found.</p>
{% else %}
    <table class="table" style="border:solid 1px black">
    <thead>
        <tr>
            <th>site name</th>
        </tr>
    </thead>
    <tbody>
    {% for site in sites %}
        <tr>
          <td><a href="{% url 'crawl:image_list' site.site_name %}">{{ site.site_name }}({{ site.icount }})</a></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endif %}
</div>

{% endblock %}

crawl/templates/list.html
{% extends "base.html" %}

{% block head %}
<style>
a.pop:hover {
  position: relative;
  text-decoration: none;
}
a.pop > img {
  width: 100px;
}
a.pop span {
  display: none;
  position: absolute;
  top: 1em;
  left: 0;
}
a.pop:hover span {
  border: none;
  display: block;
  width: 300px;
}
</style>
{% endblock %}

{% block content %}

<h2>images</h2>

<div><a href="{% url 'crawl:index' %}">back</a></div>

<div class="table-responsive">
{% if not items %}
    <p>Item not found.</p>
{% else %}
    {% include "_pagination.html" with items=items %}
    <table class="table" style="border:solid 1px black">
    <thead>
        <tr>
            <th>image</th>
            <th><a href="{% url 'crawl:image_list' sitename 'v' %}">Violence<br />(暴力表現)</a></th>
            <th><a href="{% url 'crawl:image_list' sitename 'a' %}">Adult<br />(アダルト)</a></th>
            <th><a href="{% url 'crawl:image_list' sitename 's' %}">Spoof<br />(なりすまし)</a></th>
            <th><a href="{% url 'crawl:image_list' sitename 'm' %}">Medical<br />(グロ)</a></th>
            <th>page title</th>
        </tr>
    </thead>
    <tbody>
    {% for item in items %}
        <tr>
            <td><a href="{{ item.url }}" class="pop"><img src="{{ item.url }}" alt="" />
                <span><img src="{{ item.url }}" alt="" width="300" /></span></a>
            </td>
            {% include "_level.html" with lv=item.eval_violence %}
            {% include "_level.html" with lv=item.eval_adult %}
            {% include "_level.html" with lv=item.eval_spoof %}
            {% include "_level.html" with lv=item.eval_medical %}
            <td>
                <a href="{{ item.page_url }}">{{ item.page_title }}</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% include "_pagination.html" with items=items %}
{% endif %}
</div>

{% endblock %}